import { CategoryType, ProductType } from "./types";

export const sampleCategories: Omit<CategoryType, "_id">[] = [
    { name: "Hair Care", slug: "hair-care", image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=200&h=200&fit=crop" },
    { name: "Skin Care", slug: "skin-care", image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=200&h=200&fit=crop" },
    { name: "Lipstick", slug: "lipstick", image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=200&h=200&fit=crop" },
    { name: "Face Pack", slug: "face-pack", image: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=200&h=200&fit=crop" },
    { name: "Blusher", slug: "blusher", image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=200&h=200&fit=crop" },
    { name: "Natural", slug: "natural", image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=200&h=200&fit=crop" },
    { name: "Body Care", slug: "body-care", image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=200&h=200&fit=crop" },
    { name: "Eyes", slug: "eyes", image: "https://images.unsplash.com/photo-1583241800698-e8ab01830e07?w=200&h=200&fit=crop" },
    { name: "Nails", slug: "nails", image: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=200&h=200&fit=crop" },
];

export const sampleProducts: Omit<ProductType, "_id">[] = [
    {
        name: "Rose Petal Moisturizer",
        slug: "rose-petal-moisturizer",
        description: "Indulge your skin with the luxurious Rose Petal Moisturizer. Infused with pure rose extracts and hyaluronic acid, this lightweight formula deeply hydrates while leaving a delicate floral scent. Perfect for all skin types, it absorbs quickly without any greasy residue, giving you a dewy, radiant glow that lasts all day.",
        shortDescription: "Luxurious hydrating moisturizer with pure rose extracts",
        price: 899,
        discountPrice: 649,
        images: [
            "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600&h=600&fit=crop",
            "https://images.unsplash.com/photo-1570194065650-d99fb4d38834?w=600&h=600&fit=crop",
        ],
        category: "skin-care",
        stock: 45,
        sku: "SC-RP-001",
        ratings: 4.5,
        reviews: [
            { user: "Priya S.", rating: 5, comment: "Amazing moisturizer! My skin feels so soft.", createdAt: "2025-12-01" },
            { user: "Anita K.", rating: 4, comment: "Love the rose scent, very hydrating.", createdAt: "2025-11-15" },
        ],
        isFeatured: true,
        createdAt: "2025-10-01",
    },
    {
        name: "Velvet Matte Lipstick - Cherry Red",
        slug: "velvet-matte-lipstick-cherry-red",
        description: "Make a bold statement with our Velvet Matte Lipstick in Cherry Red. This ultra-pigmented formula delivers rich, true color in a single swipe. The creamy texture glides on smoothly and sets to a comfortable matte finish that lasts up to 12 hours without drying your lips.",
        shortDescription: "Ultra-pigmented matte lipstick with 12-hour wear",
        price: 599,
        discountPrice: 449,
        images: [
            "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&h=600&fit=crop",
            "https://images.unsplash.com/photo-1631214500115-598fc2cb8ada?w=600&h=600&fit=crop",
        ],
        category: "lipstick",
        stock: 120,
        sku: "LP-VM-001",
        ratings: 4.8,
        reviews: [
            { user: "Meera R.", rating: 5, comment: "Best matte lipstick I've ever used!", createdAt: "2025-12-10" },
        ],
        isFeatured: true,
        createdAt: "2025-10-05",
    },
    {
        name: "Argan Oil Hair Serum",
        slug: "argan-oil-hair-serum",
        description: "Transform frizzy, damaged hair into silky, shiny locks with our premium Argan Oil Hair Serum. Enriched with 100% organic argan oil and vitamin E, this lightweight serum tames flyaways, adds brilliant shine, and protects hair from heat damage up to 230°C.",
        shortDescription: "Premium argan oil serum for silky, frizz-free hair",
        price: 749,
        discountPrice: 549,
        images: [
            "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&h=600&fit=crop",
            "https://images.unsplash.com/photo-1519735777090-ec97162dc266?w=600&h=600&fit=crop",
        ],
        category: "hair-care",
        stock: 67,
        sku: "HC-AO-001",
        ratings: 4.3,
        reviews: [],
        isFeatured: true,
        createdAt: "2025-10-10",
    },
    {
        name: "Golden Glow Face Pack",
        slug: "golden-glow-face-pack",
        description: "Reveal your inner glow with the Golden Glow Face Pack. This luxurious Ayurvedic formula combines turmeric, sandalwood, and 24K gold particles to brighten dull skin, minimize pores, and give you a radiant complexion. Suitable for all skin types.",
        shortDescription: "Ayurvedic face pack with turmeric and 24K gold",
        price: 499,
        discountPrice: 349,
        images: [
            "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&h=600&fit=crop",
        ],
        category: "face-pack",
        stock: 89,
        sku: "FP-GG-001",
        ratings: 4.6,
        reviews: [
            { user: "Sneha M.", rating: 5, comment: "My skin glows after every use!", createdAt: "2025-11-20" },
        ],
        isFeatured: true,
        createdAt: "2025-10-15",
    },
    {
        name: "Shimmer Blush Palette",
        slug: "shimmer-blush-palette",
        description: "Create stunning cheek looks with our Shimmer Blush Palette featuring 6 gorgeous shades from soft peach to deep berry. The silky, buildable formula blends effortlessly for a natural flush or dramatic glam look. Infused with vitamin E for skin-loving benefits.",
        shortDescription: "6-shade shimmer blush palette with vitamin E",
        price: 1299,
        discountPrice: 999,
        images: [
            "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600&h=600&fit=crop",
            "https://images.unsplash.com/photo-1599733589046-10c7e577d2e7?w=600&h=600&fit=crop",
        ],
        category: "blusher",
        stock: 34,
        sku: "BL-SP-001",
        ratings: 4.7,
        reviews: [],
        isFeatured: true,
        createdAt: "2025-10-20",
    },
    {
        name: "Organic Aloe Vera Gel",
        slug: "organic-aloe-vera-gel",
        description: "Pure, organic aloe vera gel that soothes, hydrates, and heals. Multi-purpose formula perfect for face, body, and hair. Certified organic with no added chemicals, artificial colors, or fragrances. Helps with sunburn, acne, dry skin, and even as a natural hair styling gel.",
        shortDescription: "100% organic multi-purpose aloe vera gel",
        price: 349,
        discountPrice: 249,
        images: [
            "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&h=600&fit=crop",
        ],
        category: "natural",
        stock: 200,
        sku: "NT-AV-001",
        ratings: 4.4,
        reviews: [
            { user: "Riya P.", rating: 4, comment: "Great natural product, love it!", createdAt: "2025-12-05" },
        ],
        isFeatured: true,
        createdAt: "2025-10-25",
    },
    {
        name: "Coconut Body Butter",
        slug: "coconut-body-butter",
        description: "Deeply nourish and pamper your skin with our rich Coconut Body Butter. Made with virgin coconut oil, shea butter, and cocoa butter, this ultra-thick formula locks in moisture for 48 hours. The tropical coconut scent will transport you to paradise.",
        shortDescription: "Ultra-rich body butter with virgin coconut oil",
        price: 599,
        discountPrice: 449,
        images: [
            "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&h=600&fit=crop",
        ],
        category: "body-care",
        stock: 56,
        sku: "BC-CB-001",
        ratings: 4.2,
        reviews: [],
        isFeatured: true,
        createdAt: "2025-11-01",
    },
    {
        name: "Smokey Eye Palette",
        slug: "smokey-eye-palette",
        description: "Create mesmerizing eye looks with our professional Smokey Eye Palette. Features 12 highly pigmented shades in matte, shimmer, and metallic finishes. From everyday neutral looks to dramatic smokey eyes, this palette has everything you need.",
        shortDescription: "12-shade professional eye shadow palette",
        price: 1499,
        discountPrice: 1099,
        images: [
            "https://images.unsplash.com/photo-1583241800698-e8ab01830e07?w=600&h=600&fit=crop",
            "https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?w=600&h=600&fit=crop",
        ],
        category: "eyes",
        stock: 41,
        sku: "EY-SE-001",
        ratings: 4.9,
        reviews: [
            { user: "Kavita J.", rating: 5, comment: "The pigmentation is incredible!", createdAt: "2025-12-15" },
        ],
        isFeatured: true,
        createdAt: "2025-11-05",
    },
    {
        name: "Gel Nail Polish Set",
        slug: "gel-nail-polish-set",
        description: "Get salon-quality nails at home with our Gel Nail Polish Set. Includes 6 stunning shades from classic nudes to bold pinks. Long-lasting formula that stays chip-free for up to 14 days. Easy to apply, beautiful to wear.",
        shortDescription: "6-piece gel nail polish set with salon finish",
        price: 999,
        discountPrice: 799,
        images: [
            "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&h=600&fit=crop",
        ],
        category: "nails",
        stock: 78,
        sku: "NL-GP-001",
        ratings: 4.1,
        reviews: [],
        isFeatured: false,
        createdAt: "2025-11-10",
    },
    {
        name: "Vitamin C Brightening Serum",
        slug: "vitamin-c-brightening-serum",
        description: "Brighten and even out your skin tone with our potent Vitamin C Brightening Serum. Formulated with 20% vitamin C, niacinamide, and hyaluronic acid, this serum fights dark spots, fine lines, and dullness while providing deep hydration.",
        shortDescription: "Potent 20% vitamin C serum for brighter skin",
        price: 1199,
        discountPrice: 899,
        images: [
            "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&h=600&fit=crop",
        ],
        category: "skin-care",
        stock: 92,
        sku: "SC-VC-001",
        ratings: 4.7,
        reviews: [
            { user: "Deepa T.", rating: 5, comment: "Visible results in just 2 weeks!", createdAt: "2025-11-25" },
        ],
        isFeatured: false,
        createdAt: "2025-11-15",
    },
    {
        name: "Keratin Hair Mask",
        slug: "keratin-hair-mask",
        description: "Revive dry, damaged hair with our intensive Keratin Hair Mask. Infused with keratin protein, argan oil, and biotin, this deep conditioning treatment restores strength, elasticity, and shine in just 10 minutes.",
        shortDescription: "Intensive keratin treatment for damaged hair",
        price: 699,
        discountPrice: 499,
        images: [
            "https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=600&h=600&fit=crop",
        ],
        category: "hair-care",
        stock: 110,
        sku: "HC-KM-001",
        ratings: 4.5,
        reviews: [],
        isFeatured: false,
        createdAt: "2025-11-20",
    },
    {
        name: "Nude Matte Lipstick Collection",
        slug: "nude-matte-lipstick-collection",
        description: "Find your perfect nude with our curated collection of 4 nude matte lipsticks. From warm caramel to cool mauve, these transfer-proof formulas keep your lips looking flawless from morning to night.",
        shortDescription: "4-piece nude lipstick collection",
        price: 1599,
        discountPrice: 1199,
        images: [
            "https://images.unsplash.com/photo-1631214500115-598fc2cb8ada?w=600&h=600&fit=crop",
        ],
        category: "lipstick",
        stock: 55,
        sku: "LP-NM-001",
        ratings: 4.6,
        reviews: [
            { user: "Pooja V.", rating: 5, comment: "All four shades are gorgeous!", createdAt: "2025-12-01" },
        ],
        isFeatured: false,
        createdAt: "2025-11-25",
    },
];
